# https://docs.docker.com/compose/compose-file/05-services/
version: '3'
services:
    db:
        image: postgres:15-alpine3.18
        profiles: ["infra"]
        container_name: ${POSTGRES_HOST}
        environment:
            POSTGRES_PASSWORD: postgres_password
            # 아래 설정은 github workflow 스크립트(test-coverage.yaml)에서는 동작하지 않는다.
            # POSTGRES_USER: ${POSTGRES_USERNAME}
            # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            # POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - '${POSTGRES_PORT}:5432'
        networks:
            - default

    redis:
        image: redis:7.0-alpine
        profiles: ["infra"]
        container_name: ${REDIS_HOST}
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - default

    mongo:
        image: mongo:7
        profiles: ["infra"]
        container_name: ${MONGO_HOST}
        ports:
            - ${MONGO_PORT}:27017
        networks:
            - default

    service:
        image: $PROJECT_NAME
        build: .
        profiles: ["service"]
        container_name: $PROJECT_NAME
        environment:
            - NODE_ENV=production
        env_file: .env.development
        volumes:
            - ./logs:/app/logs
        logging:
            options:
                max-size: '10m'
                max-file: '3'
        networks:
            - default

networks:
    default:
        external: true
        name: ${PROJECT_NAME}
