# https://docs.docker.com/compose/
version: '3'
services:
    db:
        image: postgres:15-alpine3.18
        profiles: ["infra"]
        container_name: ${TYPEORM_HOST}
        environment:
            POSTGRES_DB: ${TYPEORM_DATABASE}
            POSTGRES_USER: ${TYPEORM_USERNAME}
            POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
        ports:
            - '${TYPEORM_PORT}:5432'
        networks:
            - default

    redis:
        image: redis:7.0-alpine
        profiles: ["infra"]
        container_name: ${CACHE_HOST}
        ports:
            - ${CACHE_PORT}:6379
        networks:
            - default

    service:
        build: .
        profiles: ["service"]
        container_name: $PROJECT_NAME
        environment:
            - NODE_ENV=production
        env_file: .env.development
        volumes:
            - ./logs:/app/logs
        logging:
            options:
                max-size: '10m'
                max-file: '3'
        networks:
            - default

networks:
    default:
        external: true
        name: ${PROJECT_NAME}
