export * from './customers.controller'
export * from './movies.controller'
export * from './payments.controller'
export * from './showing.controller'
export * from './showtimes.controller'
export * from './storage-files.controller'
export * from './theaters.controller'
export * from './tickets.controller'
