version: '3'
services:
    nest-seed-db:
        image: postgres:15-alpine3.18
        container_name: ${TYPEORM_HOST}
        environment:
            POSTGRES_PASSWORD: postgres_password
            # 아래 설정은 github workflow에서는 할 수 없다.
            # POSTGRES_USER: ${TYPEORM_USERNAME}
            # POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
            # POSTGRES_DB: ${TYPEORM_DATABASE}
        ports:
            - '${TYPEORM_PORT}:5432'
        networks:
            - default

    nest-redis:
        image: redis:7.0-alpine
        container_name: ${CACHE_HOST}
        ports:
            - ${CACHE_PORT}:6379
        networks:
            - default

networks:
    default:
        external: true
        name: ${PROJECT_NAME}
