#!/bin/bash
set -e

psql -U "$POSTGRES_USER" -d $POSTGRES_DB <<-EOSQL
    CREATE SCHEMA $POSTGRES_SCHEMA AUTHORIZATION $POSTGRES_USER;
    GRANT ALL ON SCHEMA $POSTGRES_SCHEMA TO $POSTGRES_USER WITH GRANT OPTION;
EOSQL
