# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
name: Test and Coverage

on:
    # main 브렌치를 대상으로 하는 pull request가 create/update하면 실행된다
    pull_request:
        branches: ['main']
    # merge pull request하면 실행된다
    push:
        branches: ['main']

jobs:
    test-coverage:
        runs-on: ubuntu-latest

        container: node:lts-bullseye

        env:
            NODE_ENV: development
            WORKSPACE_ROOT: ${{ github.workspace }}

        steps:
            - name: Update Packages
              run: apt-get update

            - name: Install Docker
              run: apt-get install -y docker.io

            - name: Install Tools
              run: apt-get install -y jq bash postgresql

            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            # - name: Initialize Workflow Environment
            #   run: bash scripts/init_github_workflow.sh
            - name: Initialize Workflow Environment
              run: bash scripts/init_dev_env.sh

            - name: Run Tests and Coverage
              run: npm run test:all
