# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
name: Test and Coverage

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        container: node:lts-alpine

        services:
            postgres:
                image: postgres:15-alpine3.18
                # 아래처럼 volumes은 설정할 수 없다. workflow는 git clone을 하기전에 서비스를 먼저 실행한다.
                # 그래서 /scripts가 존재하지 않는 상태에서 맵핑하게 된다.
                # volumes:
                # - ${{ github.workspace }}/scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
                env:
                    POSTGRES_PASSWORD: postgres_password
            redis:
                image: redis

        env:
            NODE_ENV: development
            WORKSPACE_ROOT: ${{ github.workspace }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install Tools
              run: apk add -f jq bash postgresql

            - name: Initialize Workflow Environment
              run: bash scripts/init_github_workflow.sh

            - name: Run Tests and Coverage
              run: npm run test:all
