name: Test and Coverage

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            nest-seed-db:
                image: postgres:15
                env:
                    POSTGRES_USER: testuser
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: nestdb
                ports:
                    - 5432:5432

            nest-redis:
                image: redis
                ports:
                    - 6379:6379

        env:
            NODE_ENV: development

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install jq
              run: sudo apt-get install -y jq

            - name: Create logs folder
              run: mkdir -p ./logs

            - name: Install Dependencies
              run: npm install

            - name: Run Tests and Coverage
              run: npm run test:all

            - name: Check Coverage and Send Email If Below 100%
              run: |
                  COVERAGE_LINES=$(jq '.total.lines.pct' ./coverage/coverage-summary.json)
                  COVERAGE_STATEMENTS=$(jq '.total.statements.pct' ./coverage/coverage-summary.json)
                  COVERAGE_FUNCTIONS=$(jq '.total.functions.pct' ./coverage/coverage-summary.json)
                  COVERAGE_BRANCHES=$(jq '.total.branches.pct' ./coverage/coverage-summary.json)
                  COVERAGE_BRANCHES_TRUE=$(jq '.total.branchesTrue.pct' ./coverage/coverage-summary.json)

                  if (( $(echo "$COVERAGE_LINES < 100" | bc -l) )) || \
                    (( $(echo "$COVERAGE_STATEMENTS < 100" | bc -l) )) || \
                    (( $(echo "$COVERAGE_FUNCTIONS < 100" | bc -l) )) || \
                    (( $(echo "$COVERAGE_BRANCHES < 100" | bc -l) )) || \
                    (( $(echo "$COVERAGE_BRANCHES_TRUE < 100" | bc -l) )); then

                    echo "One of the coverage metrics is below 100%, failing the workflow."
                    exit 1
                  fi
