name: Test and Coverage

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        container: node:lts-alpine

        services:
            nest-seed-db:
                image: postgres:15-alpine3.18
                # 아래처럼 설정할 수 없다. workflow는 git clone을 하기전에 서비스를 먼저 실행한다.
                # 그래서 /scripts가 존재하지 않는 상태에서 맵핑하게 된다.
                # volumes:
                # - ${{ github.workspace }}/scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
                env:
                    POSTGRES_PASSWORD: postgres_password
                    POSTGRES_DB: nestdb

            nest-redis:
                image: redis

        env:
            NODE_ENV: development

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install Tools
              run: apk add -f jq bash bash-doc bash-completion postgresql bc

            - name: Create logs folder
              run: mkdir -p ./logs

            - name: set allow schema reset
              run: bash scripts/set_allow_schema_reset.sh

            - name: Init DB
              run: bash scripts/init_database.sh

            - name: Install Dependencies
              run: npm install

            - name: Run Tests and Coverage
              run: npm run test:all
